name: ffibindings
description: dart:ffi bindings example for the cross-platform core.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^2.1.0
